### ISSUE TITLE
Support Optional Chaining in Rules

### ISSUE THREAD

**Issue by bradzacher** [typescript-eslint/typescript-eslint#1051]
Spinning off of #1033

Rules that need to have support added for optional chaining.
This list was based on a simple grep for `MemberExpression` and `CallExpression`, I haven't validated anything beyond that. There are probably extra rules that could do with support as well that don't check `MemberExpression` and `CallExpression`.

Rules that require a simple one-line change (i.e. adding a selector):
- [x] consistent-type-assertions (#1253)
- [x] explicit-function-return-type (#1253)
- [x] func-call-spacing (#1253)
- [x] no-array-constructor (#1253)
- [x] no-floating-promises (#1253)
- [x] no-inferrable-types (#1253)
- [x] no-misused-promises (#1253)
- [x] no-require-imports (#1253)
- [x] no-var-requires (#1253)
- [x] prefer-for-of (#1253)
- [x] prefer-includes (#1253)
- [x] prefer-readonly (#1253)
- [x] prefer-regexp-exec (#1253)
- [x] prefer-string-starts-ends-with (#1357)
- [x] require-array-sort-compare (#1363)
- [x] unbound-method (#1363)

Rules that require a larger enhancement to support (i.e. new feature in rule):
- [x] no-unnecessary-condition (#1315)

Extension rules that will be a pain to update (i.e. base extension rewrite):
- [ ] indent / indent-new-do-not-use
- [ ] no-extra-parens
    - This one will be a huge pain, and I believe it will involve us duplicating the base rule. The logic is relatively complex, so this is a non-trivial task.
- [ ] no-unused-vars

Broken rules due to ESLint not supporting the new AST nodes:
- [x] camelcase #1196
- [X] no-restricted-globals #1090
- [X] no-undef #1116
- [X] no-unused-expressions #1138
- [X] no-use-before-define #1104

**Comment by jeroenvisser101** [comment]
Can you add `no-use-before-define`, this code fails:

```ts
const updatedAt = data?.updatedAt;
// 'updatedAt' was used before it was defined. (@typescript-eslint/no-use-before-define)
```

**Comment by bradzacher** [comment]
This is issue about _enhancing_ rules by adding support for the new AST.

could you raise a separate issue for that?
That is specifically a bug that's been introduced from the 2.4 parsing AST

**Comment by jeroenvisser101** [comment]
@bradzacher Ah, that's fine, will open an issue now :)

**Comment by hisuwh** [comment]
I'm getting a no-unused-expressions linting error on a line like this:
```ts
someFunction?.()
```

**Comment by bradzacher** [comment]
please raise a new issue @hisuwh

**Comment by bradzacher** [comment]
Looking into it - `no-extra-parens` is going to require a much bigger change because of the current implementation.

**Comment by kevinhylant** [comment]
Any timeline on when this and https://github.com/typescript-eslint/typescript-eslint/issues/1052 might be completed?

**Comment by bradzacher** [comment]
We are a community run project, meaning we rely on community support to get things done outside of critical bugfixes or core infrastructure.
So the timeline is "whenever someone feels like they need this done, and gets around to it".

Happy to accept a PR if there's something missing that is important to you.

**Comment by disovi** [comment]
Maybe **no-unnecessary-condition** should also support optional chaining?
Example
```typescript
const foo = { bar: 3 };
console.log(foo?.bar); // Unnecessary conditional
```

**Comment by bradzacher** [comment]
https://github.com/typescript-eslint/typescript-eslint/pull/1315
