### ISSUE TITLE
ESLint v7

### ISSUE THREAD

**Issue by bradzacher** [typescript-eslint/typescript-eslint#1550]
ESLint has v7 released.
https://eslint.org/blog/2020/05/eslint-v7.0.0-released

I went through the change list, and below are a list of changes I think we need to look into for full support:

Dependencies:
- [x] `Breaking: drop Node.js 8 support (refs eslint/rfcs#44) (#12700)`
  - Tracked locally in #1420

Tests:
- [x] `Breaking: RuleTester Improvements (refs eslint/rfcs#25) (#12955)`
  - This will likely break many of our tests.
- [x] `Breaking: Test with an unknown error property should fail in RuleTester (#12096)`
  - Could break some of our tests.
- [x] `Update: Allow testing Suggestions with data in RuleTester (fixes #12606) (#12635)`
  - Didn't know this wasn't checked! Might break some of our tests.

Functionality:
- [x] `Breaking: some rules recognize bigint literals (fixes #11803) (#12701)`
  - Will want to make sure our extension is still compatible
- [x] `Breaking: Add new rules to eslint:recommended (fixes #12911) (#12920)`
  - We will want to review it so we can update ours accordingly #1423

Extension rules:
- [x] Message IDs
  - `Chore: Refactor to use messageId in a number of rules (#12715)`
  - `Chore: use ids for messages (#12859)`
- [x] `Update: Improve report location for space-before-function-paren (#13128)`
- [x] `Fix: func-call-spacing "never" reports wrong message (fixes #13190) (#13193)`
- `no-magic-numbers`
  - [x] `Update: stricter array index check in no-magic-numbers (fixes #12845) (#12851)`
  - [x] `Update: fix no-magic-numbers false negative with ignoreArrayIndexes (#12805)`
- `no-implied-eval`
  - [x] `Update: support globalThis in no-implied-eval (fixes #12670) (#13105)`
  - [x] `Update: consider env in no-implied-eval (fixes #12733) (#12757)`
- `no-extra-parens`
  - [x] `Breaking: Check assignment targets in no-extra-parens (#12490)`
  - [x] `Update: report double extra parens in no-extra-parens (fixes #12127) (#12697)`
  - [x] `Update: fix no-extra-parens CallExpression#callee false negatives (#12743)`
  - [x] `Fix: no-extra-parens export default sequence expression false positive (#13096)`
  - [x] `Fix: fix inconsistently works option in no-extra-parens (fixes #12717) (#12843) `
- `no-empty-function`
  - [x] `Update: Improve report location for no-empty-function (refs #12334) (#13121)`
  - [x] `Fix: added async in allow method in no-empty-function (fixes #12768) (#13036)`

Docs:
- [ ] `Breaking: lint overrides files (fixes #10828, refs eslint/rfcs#20) (#12677)`
  - You no longer need `--ext` if you specify `overrides: { files: ["*.ts"], ... }`
  - Do we want to update our docs for this - we could now generally advise that you use an overrides for `ts` files?
    - Unsure if that's actually better than using the cli flag.
- [x] `Update: no-void add an option to allow void as a statement (#12613)`
  - We can update the docs for `no-floating-promises` now

**Comment by bradzacher** [comment]
This change has been released to NPM on the `v3-rc` tag.
It is part of the upcoming major release: https://github.com/typescript-eslint/typescript-eslint/releases/tag/v3.0.0-alpha.23

We'll probably let that soak for a week or so to give people time to test it before the full release.

**Comment by Sparticuz** [comment]
Looks like it's tagged `rc-v3`
