### ISSUE TITLE
2.0.0 Breaking Changes

### ISSUE THREAD

**Issue by bradzacher** [typescript-eslint/typescript-eslint#501]
I wanted somewhere to keep track of the breaking changes we should make as part of a 2.0.0 release.

Deprecated Rules:
- [x] (pr #739) remove deprecated rule `prefer-interface` (replaced by `consistent-type-definitions`)
- [x] (pr #739) remove deprecated rule `no-triple-slash-reference` (replaced by `triple-slash-reference`)
- [x] (pr #731) remove deprecated rule `no-angle-bracket-type-assertion` (replaced by `consistent-type-assertions`)
- [x] (pr #731) remove deprecated rule `no-object-literal-type-assertion` (replaced by `consistent-type-assertions`)

Misc:
- [x] (pr #645) Support eslint 6 (drop node 6 support)
- [x] (pr #594) kill `isTypescriptFile` checks #524
- [x] (pr #731) generalize [`no-angle-bracket-type-assertion`](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/no-angle-bracket-type-assertion.md) (#332) and merge in [`no-object-literal-type-assertion `](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/no-object-literal-type-assertion.md)
- [x] (pr #760) protection against most common performance pitfall
- [x] (pr #831) `explicit-function-return-type` `allowExpressions` shouldn't ignore `export default () => {}`
- ~~rename `@typescript-eslint/experimental-utils` to `@typescript-eslint/utils` (https://github.com/typescript-eslint/typescript-eslint/pull/425#pullrequestreview-235352249)~~ will do in v3
- ~~look into renaming a number of rules #203~~ will do with a later major bump..

Recommended stuff:
- [x] reevaluate rule defaults
  - [x] (pr #729) make `explicit-function-return-type` more relaxed by default, as it's the standard usage (#493)
  - [x] (#733)  Remove the `allowAny` option from the `promise-function-async` rule and make it the default (from comment below)
- [x] (pr #729) update the recommended rule set with new rules (and remove some rules) #651
- [ ] (pr #846) split the recommended into a base set not requiring type info, and an extension set requiring type info, so people can have a fast experience by default.

**Comment by bradzacher** [comment]
Potential other changes that need discussions:
- look at merging [`no-unnecessary-type-assertion`](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/no-unnecessary-type-assertion.md) and [`no-inferrable-types`](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/no-inferrable-types.md)

**Comment by ldrick** [comment]
@bradzacher Maybe adding all.json to configs #298 could be part auf 2.0.0?

**Comment by bradzacher** [comment]
nope! `all.json` is an entirely new config, so it's just a minor bump to add it.
I'll get back to reviewing the PR for it v soon!

**Comment by ldrick** [comment]
Maybe it is possible to remove [Node 6 support](https://nodejs.org/en/about/releases/)?
And having a look at dependencies `yarn outdated`?

**Comment by sindresorhus** [comment]
- Remove the `allowAny` option from the `promise-function-async` rule and make it the default. https://github.com/typescript-eslint/typescript-eslint/pull/553

**Comment by IlCallo** [comment]
I'm sorry to be that type of dev but... Do you have a ETA/roadmap for v2.0.0?

We are working to [move Quasar TS extension](https://github.com/quasarframework/app-extension-typescript/issues/18) from TSLint to ESLint using this package, but some things you'll resolve in v2 are things we'll need asap.
So we are trying to understand if waiting for v2 is an option or we shall fork the repo and apply the fixes we care the most right away, keeping it updated with upstream

**Comment by bradzacher** [comment]
@IlCallo - what PRs are you waiting for specifically?

Having a quick look at the linked issue..
- `isTypescriptFile` only affects two rules, so that shouldn't stop you (#524)
- FYI Vue files have somewhat nebulous support right now because of weird interactions with how `vue-eslint-parser` interacts with perf optimisations we added (#404).
    - I'd love someone who's familiar with vue to dig in more into the problem - as I have never used it before and have no idea how vue works. There are some ideas listed in #404.

**Comment by IlCallo** [comment]
#524 is the main problem we have, because if doesn't allow people working on SFC to access your linting capabilities, forcing to separate the typescript part into a second file.

It's not "blocking" in any way, we'll probably migrate to typescript-eslint anyway, but we'd like to have that problem solved by day-0 when we release the update, that's why we were thinking about forking the repo :)
Plus some other problems we can try to fix in our fork and then send upstream.

I was asking a roadmap/ETA to better coordinate the efforts

**Comment by bradzacher** [comment]
`isTypescriptFile` only blocks two rules - `explicit-member-accessibility` and `explicit-function-return-type`. The rest of the repo doesn't use the utility function. It's been in those rules for ages back before eslint `overrides` were widely used.

The optimistic plan is to look into handling all of the breaking changes within the next week or two. But as we're all volunteer maintaners, life could get in the way of that..

Note #404 will hard block you guys though. You cannot migrate to `>=1.5.0`, because `1.5.0` was the version that essentially broke vue support.

**Comment by IlCallo** [comment]
Ok, I'll take a closer look to #404 and see if I can help to resolve that

**Comment by JamesHenry** [comment]
FYI for any subscribers to this issue, we have begun merging breaking change PRs and the canary releases (i.e. `master`) are now on 2.x.x.

**We will likely promote v2.x.x to stable in one week**. We won't leave such a big gap until v3.x.x but we also want to be mindful of churn, so if you do have breaking changes you want to see now is the time to champion/implement them :)

Please also do us a favour and install from `@canary` and report any issues.

Thanks!

**Comment by corbinu** [comment]
Installed canary been using it for a 2 days and seems fine

**Comment by JamesHenry** [comment]
Thanks @corbinu - I have just published a new canary manually: `2.0.0-alpha.3`

**Comment by waitingsong** [comment]
Is there a duplicate item in the first post ?

<img width="642" alt="2019-07-25_095808" src="https://user-images.githubusercontent.com/1763067/61840166-e0357900-aec2-11e9-9d49-b75833d43f78.png">

It seems one of them should be `no-object-literal-type-assertion`.

**Comment by JamesHenry** [comment]
Unfortunately we haven't quite been able to get everything wrapped up within the week. We will let the updated v2 alphas bed in for one more week and then publish v2 to latest next weekend.

Please help us by testing out the latest alphas on your codebases!

- `2.0.0-alpha.4` **has been published** and contains the new protection against performance issues which occur when files are being linted which fall outside your TypeScript Programs (#760) 

- `2.0.0-alpha.5` has **not** yet been published but will contain the updates to the recommended config. We will publish this as soon as it's ready.

**Comment by trivikr** [comment]
Thanks @JamesHenry for follow-up.
Is there any update on v2 release this week?

**Comment by a-tarasyuk** [comment]
> Is there any update on v2 release this week?

+1

**Comment by JamesHenry** [comment]
I'm not very well at the moment, so we are pushing the release back a few more days. I have just published `2.0.0-alpha.5` which contains all the commits to master since the last canary, so nobody should be blocked in any way

**Comment by trivikr** [comment]
Take care @JamesHenry!
Health always comes first 😊

**Comment by bradzacher** [comment]
[v2.0.0 is released! 🎉 ](https://github.com/typescript-eslint/typescript-eslint/releases/tag/v2.0.0)
