### ISSUE TITLE
Bug: [prefer-optional-chain] Crashes when parsing an `import.meta` member with both the `||` and `!` operators

### ISSUE THREAD

**Issue by allezxandre** [typescript-eslint/typescript-eslint#6000]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Abug+label%3A%22package%3A+eslint-plugin%22) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/docs/linting/troubleshooting) and my problem is not listed.

### Playground Link

https://typescript-eslint.io/play/#ts=4.8.4&sourceType=module&code=JYMwBAFAhMC2AOB7ATgFwHSwKaoIboFdkAbMAHzLFWQKwEowBjRAOwGdFit1jEBzCACIAElmK9BdANxA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6Y6RAM0WloHsalfkwCG8WmQAWo5uigB3UdCaRwYAL4gNQA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA

### Repro Code

```typescript
if (!import.meta.url || true) console.log("Hello");
```

### ESLint Config

```javascript
module.exports = {
  parser: "@typescript-eslint/parser",
  rules: {
    "@typescript-eslint/prefer-optional-chain": "warn",
  },
};
```

### tsconfig

```jsonc
{
  "compilerOptions": {
    "strictNullChecks": true
  }
}
```

### Expected Result

I expected ESLint to be all OK.

### Actual Result

The parser crashes:

```
Oops! Something went wrong! :(

ESLint: 8.27.0

Error: Unexpected member object type: MetaProperty
Occurred while linting /workspaces/file.ts:123
Rule: "@typescript-eslint/prefer-optional-chain"
...
```

### Versions

| package                                | version |
| -------------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin`     | `5.43.0` |
| `@typescript-eslint/parser`            | `5.43.0` |
| `TypeScript`                           | `4.8.4` |
| `ESLint`                               | `8.27.0` |
| `node`                                 | `18.11` |
