### ISSUE TITLE
ESLint Flat Config Support

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [typescript-eslint/typescript-eslint#7694]
## Overview

ESLint is adding an exciting new config system called "flat" configs: 

* Configuration files docs: https://eslint.org/docs/latest/use/configure/configuration-files-new
* Configuration migration guide: https://eslint.org/docs/latest/use/configure/migration-guide

**`@typescript-eslint/eslint-plugin` does not yet officially support ESLint flat configs.** We'd certainly like it to soon. But doing so is a nontrivial in-progress task and isn't done yet. Flat configs with TypeScript code _may_ work in your specific project. They may not. 

Tracking references:
- [x] #7273: adding type definitions to work with well-typed flat config files
- [x] https://github.com/eslint/eslint/issues/17242: upstream ESLint issue for adding the docs we need to know how to provide support
- [ ] #7935: adds support for flat config files to our tooling

If you're filing a complex / configuration issue on typescript-eslint, for now, please make sure you're using traditional ESLint configs. We'll post back in this issue once we can officially provide support for using `@typescript-eslint/eslint-plugin` with flat configs.

**Comment by so1ve** [comment]
I'm sorry for replying to this issue. I would like to ask: Currently typescript-eslint's type-aware-rules cannot work well with flat config:
```
You have used a rule which requires parserServices to be generated. You must therefore provide a value for the "parserOptions.project" property for @typescript-eslint/parser.
```
Is this an intended (or known bug)? Should I post a new issue?

**Comment by bradzacher** [comment]
As per the OP...

> @typescript-eslint/eslint-plugin does not yet officially support ESLint flat configs. We'd certainly like it to soon. But doing so is a nontrivial in-progress task and isn't done yet.
> ***Flat configs with TypeScript code may work in your specific project. They may not.***

We have not used or tested flat configs at all, and we don't know the correct style for configs and we provide no guarantees that anything works.
If properly configured, the new system is supposed to be 1:1 compatible - but we don't know for sure.

Until we have official support for flat configs - using them with our tooling is considered "no warranty provided" and our advice is to instead using a "classic" config for now.

**Comment by JoshuaKGoldberg** [comment]
@so1ve it breaks my heart to give such an unhelpful answer, but: we don't support flat configs. Any other issue filed would probably be closed as a duplicate of this one. Until the docs are filled out, we're not going to try to guesswork the right way to solve issues such as the checked rules.

**Comment by so1ve** [comment]
@JoshuaKGoldberg Never mind! I can simply disable them until typescript-eslint officially supports them :D

**Comment by pauliesnug** [comment]
+1 I'm very much looking forward to this as well as the FlatESLint config types in the TSEslint and DefinitelyTyped repos!

**Comment by ild0tt0re** [comment]
> > Instead it's better if you use eslint's compatibility tooling to work with our configs for now until we have full support.
> 
> At least in my case that wasn't working correctly because the `@typescript-eslint` rules were not only enabled on TypeScript files, giving this error:
> ```
> Error: Error while loading rule '@typescript-eslint/await-thenable': You have used a rule which requires parserServices to be generated. You must therefore provide a value for the "parserOptions.project" property for @typescript-eslint/parser.
> Occurred while linting ...js
>     at getParserServices (.../node_modules/@typescript-eslint/utils/dist/eslint-utils/getParserServices.js:29:15)
>     at create (.../node_modules/@typescript-eslint/eslint-plugin/dist/rules/await-thenable.js:47:55)
>     at Object.create (.../node_modules/@typescript-eslint/utils/dist/eslint-utils/RuleCreator.js:38:20)
>     at createRuleListeners (.../node_modules/eslint/lib/linter/linter.js:910:21)
>     at .../node_modules/eslint/lib/linter/linter.js:1081:110
>     at Array.forEach (<anonymous>)
>     at runRules (.../node_modules/eslint/lib/linter/linter.js:1018:34)
>     at Linter._verifyWithFlatConfigArrayAndWithoutProcessors (.../node_modules/eslint/lib/linter/linter.js:1745:31)
>     at Linter._verifyWithFlatConfigArray (.../node_modules/eslint/lib/linter/linter.js:1876:21)
>     at Linter.verify (.../node_modules/eslint/lib/linter/linter.js:1448:65)
> ```
> And we can't just use the typescript-eslint parser for these files too, as we want the Babel parser.

@alexeyr-ci same problem here. As workaround we wrote the last configuration object turning off this rules only for `js` files.

**Comment by bradzacher** [comment]
We have a config to help disable type-aware rules: https://typescript-eslint.io/linting/configs#disable-type-checked

Which you can apply to just JS files using overrides (aka file filters in flat configs)

**Comment by brianjenkins94** [comment]
> Instead it's better if you use eslint's compatibility tooling

Thanks, I wasn't aware of this.

**Comment by bradzacher** [comment]
It is not included in the flat config docs for some reason so not a lot of people do know. It's included in the blog posts though.

**Comment by Pilaton** [comment]
I have a monorepository [eslint-eco](https://github.com/Pilaton/eslint-eco/tree/main), which contains all the basic plugins to work with. In the monorep there is a subpackage pph, which has just a flat config with all the basic typescript-eslint rules. 
 
You can see how they are written [here](https://github.com/Pilaton/eslint-eco/blob/main/packages/base/src/configs/typescript.js).  

If you want to try the config, the documentation is [here](https://github.com/Pilaton/eslint-eco/blob/main/packages/base/README.md).

**Comment by bradzacher** [comment]
If amyone wants to use our tooling (or any tooling that hasn't updated yet) with flat configs you can do so right now without doing any dodgy stuff like pulling apart our tooling or re-defining our configs.

You can use the official compatibility tooling - [`@eslint/eslintrc`](https://www.npmjs.com/package/@eslint/eslintrc).

```ts
const { FlatCompat } = require('@eslint/eslintrc'); 

const compat = new FlatCompat({ resolvePluginsRelativeTo: __dirname });

module.exports = [
  // use our recommended config
  compat.extends("plugin:@typescript-eslint/recommended"),
  
  // use our plugin by itself
  compat.plugin("@typescript-eslint"),
  // this will define make our rules available as `@typescript-eslint/`

  // or translate an entire eslintrc style config!
  compat.config({
    extends: [
      'plugin:@typescript-eslint/recommended-type-checked',
    ],
    plugins: ['@typescript-eslint'],
    parser: '@typescript-eslint/parser',
    parserOptions: {
      project: true,
      tsconfigRootDir: __dirname,
    },
  }),
];
```

Again there's no need to jump through hoops and try to figure out how to disect our packages to attempt to reconstruct them so it works with flat configs - just use the official tooling.

However we don't recommend people use flat configs yet just because they are still not fully stable. We haven't released support yet because we have encountered crashes! The tooling is also brand new and as such there aren't any utilities to help compose configs in nice ways so it can be clunky working to migrate more complex setups.

If you want to use them - please feel free! But know that you are using a beta that doesn't yet support all valid configs and as such you may encounter crashes.

**Comment by bradzacher** [comment]
This will be releasing with our v7 release next week.
