### ISSUE TITLE
ESLint v9 Support

### ISSUE THREAD

**Issue by bradzacher** [typescript-eslint/typescript-eslint#8211]
ESLint has released v9.
- https://eslint.org/blog/2024/04/eslint-v9.0.0-released/

Note that it contains breaking changes and as such we do not currently support it. It may work or it may not.

**We are not accepting issues against v9 until we have official support - so please do not file issues with crashes or bugs for now and please do not comment on this issue telling us about crashes.**

_If you believe you have a bug when using ESLint v8 - **please file a new issue**._
_If you need some help setting up / configuring your project - **please visit our discord**._

If you'd like to help contribute towards support feel free to comment!

---

# Ongoing Work

- [x] #7694 -- #7935
- [x] https://github.com/typescript-eslint/typescript-eslint/pull/8861
- [x] https://github.com/typescript-eslint/typescript-eslint/pull/8895
- [ ] #9002

# Breaking Changes

- [x] correct camelcase rule schema for allow option
- [x] move AST traversal into SourceCode
- [x] disallow multiple configuration comments for same rule
- [x] default for enforceForClassMembers in no-useless-computed-key
- [x] no-unused-vars default caughtErrors to ‘all’: #8967
- [x] no-unused-vars varsIgnorePattern behavior with catch arguments: #8967
- [x] no-restricted-imports allow multiple config entries for same path
- [x] no-sequences rule schema correction
- [x] no-invalid-regexp make allowConstructorFlags case-sensitive
- [x] no-inner-declaration new default behaviour and option
- [x] add two more cases to no-implicit-coercion
- [x] Remove valid-jsdoc and require-jsdoc
- [x] handle --output-file for empty output when saving to disk
- [x] upgrade eslint-scope@8.0.0
- [x] configuration comments with just severity should retain options
- [x] Remove CodePath#currentSegments
- [x] remove no-inner-declarations from eslint:recommended
- [x] Rename FlatESLint to ESLint
- [x] skip running warnings in --quiet mode
- [x] Set default schema: [], drop support for function-style rules
- [x] Switch Linter to flat config by default: #8968
- [x] Parsing ‘exported’ comment using parseListConfig
- [x] Behavior of CLI when no arguments are passed
- [x] Update shouldUseFlatConfig and CLI so flat config is default
- [x] deprecate no-new-symbol, recommend no-new-native-nonconstructor
- [x] Update eslint:recommended configuration
- [x] drop support for string configurations in flat config array
- [x] Remove SourceCode#getComments()
- [x] Remove deprecated context methods
- [x] Swap FlatESLint-ESLint, FlatRuleTester-RuleTester in API #8970
- [x] remove formatters except html, json(-with-metadata), and stylish
- [x] Require Node.js ^18.18.0 || ^20.9.0 || >=21.1.0

## Changes we're treating as non-breaking

Per discussion in #8211, these augmentations fix previous gaps in the RuleTester. We'll treat them as non-breaking bug fixes so they can land in the v7 major version ahead of v8.

- [ ] [RuleTester] Rule Tester checks for missing placeholder data in the message: #9020
- [ ] [RuleTester] Stricter rule test validations: #9016
- [ ] [RuleTester] FlatRuleTester -> RuleTester: #9017
- [ ] [RuleTester] detect duplicate test cases: #9018
- [ ] [RuleTester] check for parsing errors in suggestion fixes: #9019
- [x] [RuleTester] assert suggestion messages are unique in rule testers: #8969

**Comment by JoshuaKGoldberg** [comment]
The v7 line supports ESLint v9 & flat configs 🚀. See https://typescript-eslint.io/blog/announcing-typescript-eslint-v7.

**Comment by JoshuaKGoldberg** [comment]
👋 thanks for the feedback @heymartinadams! You don't have to use the `tseslint.config` helper at all. It's just a convenience wrapper to do a bit of file mapping. See: https://typescript-eslint.io/packages/typescript-eslint#flat-config-extends.

If you think there's a better way for us to surface this in the docs, we'd happily take a [new docs issue](https://github.com/typescript-eslint/typescript-eslint/issues/new?assignees=&labels=documentation%2Ctriage&projects=&template=05-documentation-request.yml&title=Docs%3A+%3Ca+short+description+of+my+proposal%3E) suggesting how. I can see how someone reading through the first-run docs might get the wrong impression here.

**Comment by heymartinadams** [comment]
Got it, thank you @JoshuaKGoldberg! Relieved to hear that 😅  Indeed that was my impression, since this wrapper showed up right in the “Getting Started” section. I’ll post an issue 🚀 
![CleanShot 2024-02-16 at 13 17 15@2x](https://github.com/typescript-eslint/typescript-eslint/assets/11673745/939eca21-bdba-4aec-a88c-9ff8e2d26643)

**Comment by bradzacher** [comment]
If you glance at [the implementation](https://github.com/typescript-eslint/typescript-eslint/blob/main/packages%2Ftypescript-eslint%2Fsrc%2Fconfig-helper.ts) you'll see that the helper is the identity function -- if you don't use the `extends` feature it adds.

That means that writing `export default tseslint.config(...)` is semantically the same as `export default [...];`. The difference is that the latter is untyped, but the former has strict types defined - meaning your input can be checked -- mistakes will be flagged and you'll get auto-complete with each property fully documented via jsdoc.

We introduced this util because it provides a simple way for people to typecheck their configs. Otherwise people need to annotate the array with a jsdoc type which is very cumbersome and verbose:
```ts
/** @type {import('@typescript-eslint/utils').TSESLint.FlatConfigArray} */
export default [...];

// vs

export default tseslint.config(...);
```

We can definitely clarify this in the docs if it wasn't clear that the util isn't required.

**Comment by trivikr** [comment]
Heads up: The maintainers would be knowing this already, but eslint v9 is releasing today
Details in https://github.com/eslint/eslint/issues/18228

This can bring traffic to typescript-eslint repo for folks trying to upgrade, and they might just land on this issue from search.
It might be a good idea to provide a summary in this post in a comment or issue description.

**Comment by bradzacher** [comment]
v9 has officially released
https://eslint.org/blog/2024/04/eslint-v9.0.0-released/

Note that it contains breaking changes and as such we do not currently support it. It may work or it may not.

This issue tracks our official support.

Note that we are not accepting issues against v9 until we have official support - so please do not file issues with crashes or bugs for now and please do not comment on this issue telling us about crashes.

If you'd like to help contribute towards support feel free to comment!

**Comment by jamesgpearce** [comment]
Don't want to add to the noise, but did want to say thank you for being so clear and organized about what is supported and what the status is. Saved me a morning of wrestling with the immediate v9.0 fallout; I know to wait! 🙏

**Comment by the-homeless-god** [comment]
Temporary solution is

Install deps via

`npm i @typescript-eslint/eslint-plugin @typescript-eslint/parser -D --legacy-peer-deps`

Put into `.npmrc`

```
legacy-peer-deps=true
```

Be sure to understand https://github.blog/2021-02-02-npm-7-is-now-generally-available/#peer-dependencies and https://stackoverflow.com/questions/66020820/npm-when-to-use-force-and-legacy-peer-deps

Additional doc about migration to v9:

https://eslint.org/docs/latest/use/migrate-to-9.0.0

Be sure about [Node.js < v18.18, v19 are no longer supported](https://eslint.org/docs/latest/use/migrate-to-9.0.0#drop-old-node)

Also for myself I'm still using `.eslintrc` instead of a new config file. Why? Need to wait until plugin developers will finish porting.

For example, how did I changed my configs for sample frontend repo:

Before:

```json
    "@typescript-eslint/eslint-plugin": "^6.9.0",
    "@typescript-eslint/parser": "^6.9.0",
    "eslint": "^8.52.0",
    "eslint-config-airbnb": "^19.0.4",
    "eslint-plugin-import": "^2.29.0",
    "eslint-plugin-json": "^3.1.0",
    "eslint-plugin-jsx-a11y": "^6.7.1",
    "eslint-plugin-react": "^7.33.2",
    "eslint-config-prettier": "^9.0.0",
    "eslint-plugin-prettier": "^5.0.1",
```

Now:

```json
    "@typescript-eslint/eslint-plugin": "^7.5.0",
    "@typescript-eslint/parser": "^7.5.0",
    "eslint": "^9.0.0",
    "eslint-config-airbnb": "^19.0.4",
    "eslint-config-prettier": "^9.1.0",
    "eslint-plugin-import": "^2.29.1",
    "eslint-plugin-json": "^3.1.0",
    "eslint-plugin-jsx-a11y": "^6.8.0",
    "eslint-plugin-prettier": "^5.1.3",
    "eslint-plugin-react": "^7.34.1",
```

### Command:

Before 

```json
    "lint:eslint": "eslint ./packages/*/src --ext .ts,.tsx -c .eslintrc",
```

Now

```json
    "lint:eslint": "ESLINT_USE_FLAT_CONFIG=false eslint ./packages/**/**.{ts,tsx} -c .eslintrc",
```

After that you will see message

```
(node:25340) ESLintRCWarning: You are using an eslintrc configuration file, which is deprecated and support will be removed in v10.0.0. Please migrate to an eslint.config.js file. See https://eslint.org/docs/latest/use/configure/migration-guide for details.
(Use `node --trace-warnings ...` to show where the warning was created)
```

it will be reminder for you, but now you have updated version to v9.

Summary:

- `ESLINT_USE_FLAT_CONFIG=false` now is added, because `--ext` and plugins are not supported anymore, for example there are some issues with with typescript, because eslint doesn't contain point to typescript
- `legacy-peer-deps` as temporary solution to use `typescript-eslint`

Example of workable config:

```json
{
  "parser": "@typescript-eslint/parser",
  "parserOptions": {
    "project": "./tsconfig.json"
  },
  "extends": [
    "eslint:recommended",
    "prettier",
    "plugin:@typescript-eslint/recommended"
  ],
  "plugins": ["@typescript-eslint", "import"],
  "env": {
    "es6": true,
    "node": true
  },
  "ignorePatterns": [
    "dist",
    "node_modules",
    "examples",
    "scripts",
    "packages/*/package.json",
    "packages/*/tsconfig.json",
    "**/*.json",
    "**/*.png",
    "**/*.svg",
    "**/*.css",
    "**/*.scss",
    "**/*.ttf",
    "**/*.snap"
  ],
  "rules": {
    "@typescript-eslint/no-unused-vars": [
      "error",
      {
        "argsIgnorePattern": "^_",
        "varsIgnorePattern": "^_"
      }
    ],
    "@typescript-eslint/no-explicit-any": "off",
    "@typescript-eslint/ban-ts-comment": "off",
    "@typescript-eslint/no-namespace": "off",
    "no-case-declarations": ["off"],
    "import/order": [
      "error",
      {
        "newlines-between": "always-and-inside-groups",
        "groups": ["builtin", "external", "internal", "parent", "sibling"],
        "pathGroups": [
          {
            "pattern": "react",
            "group": "external",
            "position": "before"
          },
          {
            "pattern": "**/*.+(svg|png|jpg|jpeg|mp3|mp4|tiff|webp|gif)",
            "group": "sibling",
            "position": "after"
          },
          {
            "pattern": "./*.scss",
            "group": "sibling",
            "position": "after"
          }
        ],
        "pathGroupsExcludedImportTypes": [],
        "alphabetize": {
          "order": "asc"
        }
      }
    ]
  }
}
```

**Comment by the-homeless-god** [comment]
> Don't want to add to the noise, but did want to say thank you for being so clear and organized about what is supported and what the status is. Saved me a morning of wrestling with the immediate v9.0 fallout; I know to wait! 🙏

Take a loot at the top example, it works with some restrictions

**Comment by reduckted** [comment]
> If you'd like to help contribute towards support feel free to comment!

I'd be happy to help out where I can. Are there issues for any of the breaking changes that haven't been ticked off yet?

**Comment by bradzacher** [comment]
## Linter Users

ESLint v9 _should_ "just work" with typescript-eslint v7.

One thing that needs to be checked is whether or not we need to do anything to our configs to handle the `eslint:recommended` configuration changes (eg are there rules we need to disable? or extension rules we need to turn on?).

## API Users (mainly those that use `utils/ts-eslint`)

- Switch Linter to flat config by default

We'd need to look more into the difference between the before and after here as to whether it actually makes a difference for consumers of our package. If it doesn't then all good we can tick and move on! If it does then we need to figure out a path forward here with the types. EG how can we support types that depend on the version of `eslint` the user has installed?

## Rule Authors

- FlatRuleTester -> RuleTester (this impacts people using `utils/tseslint/RuleTester` only)

In the case of the `ESLint` class - eslint exports both `FlatESLint` and `LegacyESLint` which allows us to export both separately. But `RuleTester` just has one export - so we don't have the option of maintaining two versions.

A lot of people rely on the `RuleTester` class from utils. I'm considering just switching it over to our `rule-tester` package (which is a fork and thus would avoid this problem).
Otherwise I don't know how we can handle this - the two classes have completely different constructor options. 🤔

## For typescript-eslint internally

- no-unused-vars
    - default caughtErrors to ‘all’
    - varsIgnorePattern behavior with catch arguments
- RuleTester
    - Rule Tester checks for missing placeholder data in the message
    - Stricter rule test validations
    - detect duplicate test cases
    - check for parsing errors in suggestion fixes
    - assert suggestion messages are unique in rule testers

Specifically we need:
1) update our `no-unused-vars` implementation
2) to add these to the `rule-tester` implementation

But both of these require a major release so we might just punt on them for now?

TBH I'm actually okay with us updating `@typescript-eslint/rule-tester` with these changes. Yes it will cause errors in tests for people - but they're all correct errors that should have been caught previously. I think it's okay treating it [the same as a lint rule](https://typescript-eslint.io/users/versioning/#eslint-plugin) i.e. "A change to the plugins shall not be considered breaking if it: ... Adds additional checks to an existing rule that causes new reports in a small-to-medium set of cases in an average codebase".

I'd like @typescript-eslint/triage-team's thoughts on that last point though.

**Comment by karlhorky** [comment]
> ESLint v9 _should_ "just work" with typescript-eslint v7.

Ah this is great!

I just confirmed this using [the Quickstart guide in the docs](https://typescript-eslint.io/getting-started#quickstart):

```bash
➜  p mkdir a
➜  p cd a
➜  a echo '{\n  "type": "module"\n}' > package.json
➜  a pnpm add --save-dev eslint @eslint/js typescript typescript-eslint
Already up to date
Progress: resolved 121, reused 121, downloaded 0, added 0, done

devDependencies:
+ @eslint/js ^9.0.0
+ eslint ^9.0.0
+ typescript ^5.4.4
+ typescript-eslint ^7.6.0

 WARN  Issues with peer dependencies found
.
└─┬ typescript-eslint 7.6.0
  ├── ✕ unmet peer eslint@^8.56.0: found 9.0.0
  ├─┬ @typescript-eslint/eslint-plugin 7.6.0
  │ ├── ✕ unmet peer eslint@^8.56.0: found 9.0.0
  │ └─┬ @typescript-eslint/type-utils 7.6.0
  │   ├── ✕ unmet peer eslint@^8.56.0: found 9.0.0
  │   └─┬ @typescript-eslint/utils 7.6.0
  │     └── ✕ unmet peer eslint@^8.56.0: found 9.0.0
  └─┬ @typescript-eslint/parser 7.6.0
    └── ✕ unmet peer eslint@^8.56.0: found 9.0.0

Done in 2.2s
➜  a cat package.json
{
  "type": "module",
  "devDependencies": {
    "@eslint/js": "^9.0.0",
    "eslint": "^9.0.0",
    "typescript": "^5.4.4",
    "typescript-eslint": "^7.6.0"
  }
}

# Add eslint.config.js file from https://typescript-eslint.io/getting-started#step-2-configuration

➜  a pnpm eslint . --max-warnings 0
➜  a echo 'const a = 1;' > index.ts
➜  a pnpm eslint . --max-warnings 0

/Users/k/p/a/index.ts
  1:7  error  'a' is assigned a value but never used  @typescript-eslint/no-unused-vars

✖ 1 problem (1 error, 0 warnings)
```

**Comment by reduckted** [comment]
> One thing that needs to be checked is whether or not we need to do anything to our configs to handle the `eslint:recommended` configuration changes (eg are there rules we need to disable? or extension rules we need to turn on?).

These are the changes I can see.

Added:
- `no-constant-binary-expression`
- `no-empty-static-block`
- `no-new-native-nonconstructor` (replaces `no-new-symbol` - https://github.com/eslint/eslint/issues/17446)
- `no-unused-private-class-members`

Removed:
- `no-extra-semi`
- `no-inner-declarations`
- `no-mixed-spaces-and-tabs`
- `no-new-symbol`

Based on those changes, it looks like the only thing we need to change is to replace `no-new-symbol` with `no-new-native-nonconstructor` in `eslint-recommeded-raw.ts`.

**Comment by bradzacher** [comment]
@zdila this is not the place to post bug reports or ask for support. Please visit our discord to ask for help.

**Comment by JoshuaKGoldberg** [comment]
> TBH I'm actually okay with us updating `@typescript-eslint/rule-tester` with these changes.

Same, for the reasons you stated.

I'm personally much more comfortable releasing "debatable" semver changes in this way for exports primarily used by plugin authors. Folks writing ESLint plugins are a much smaller and much more high-intent audience than typical other developers.

**Comment by bradzacher** [comment]
@the-homeless-god because this thread is not about ways to circumvent your particular package manager's internal constraints.

It's a place for people to collaborate on supporting eslint v9. And as such we want to keep it focused and anything else is off topic.

**Comment by OlivierZal** [comment]
Hi @bradzacher,

It seems that `experimental` has been deprecated with VS Code ESLint latest version (https://github.com/typescript-eslint/typescript-eslint/pull/7935/files#diff-a5de3e5871ffcc383a2294845bd3df25d3eeff6c29ad46e3a396577c413bf357R13), and should be simplified as follows:

```json
"eslint.useFlatConfig": true
```

**Comment by bradzacher** [comment]
@OlivierZal feel free to file a separate repo maintenance issue and (if you're keen) raise a PR to update our config!

**Comment by JoshuaKGoldberg** [comment]
@bradzacher what does this mean?

> Switch Linter to flat config by default

AFAICT that's the only item blocking specifically `@typescript-eslint/utils` from adding `eslint@9` to its support range.

**Comment by bradzacher** [comment]
@JoshuaKGoldberg actually it's one of two (see below the line for the other)

The linter change - https://github.com/eslint/eslint/pull/17851

Essentially the linter takes in a config type in its constructor. In v8 the type defaults to one thing and in v9 it defaults to another.

Looking at the PR - from our side it's just a jsdoc change to document the defaults.

---

The other issue is `Switch FlatRuleTester-RuleTester in API`

In v8 the `RuleTester` class accepts its config in the legacy form (eg `parserOptions` directly). In v9 it accepts it in the flat form (eg `languageOptions.parserOptions`).

Because `/utils/ts-eslint/RuleTester` is a typed re-export from eslint - this complicates things for us.

**Comment by pierluigilenoci** [comment]
@bradzacher, Is there any chance we can see this moving forward?
Many projects are "stuck" in library updates because of this.

**Comment by bradzacher** [comment]
@pierluigilenoci as volunteer maintainers we are making progress whenever our time permits.

It is open for anyone to contribute to move things along faster!

**Comment by bneigher** [comment]
🙏

**Comment by js2me** [comment]
any updates ? 🤣

**Comment by DaiFudo** [comment]
When we will use new version?

**Comment by JoshuaKGoldberg** [comment]
Now that #9002 is merged, the `v8` versions of typescript-eslint starting with [v8.0.0-alpha.10](https://www.npmjs.com/package/typescript-eslint/v/8.0.0-alpha.10) now support ESLint v9. Hooray! 🙌 

**If you still have problems with typescript-eslint and ESLint v9:**

1. Please make sure you're using `typescript-eslint@8.0.0-alpha.10` or newer
2. Go through [our issue chooser](https://github.com/typescript-eslint/typescript-eslint/issues/new/choose) to file a new issue reporting your problems
    * That issue template includes _searching for existing issues matching your problem_ - please do not file duplicate issues

Note that we do not plan on backporting ESLint v9 support to v7 versions of typescript-eslint. There are a lot of breaking changes inherent to our ESLint v9 support.

If any enterprising individual wants to try onboarding _us_ in typescript-eslint to ESLint v9, #9082 tracks that as a followup.
