### ISSUE TITLE
2.0.0 Parsing Issues

### ISSUE THREAD

**Issue by bradzacher** [typescript-eslint/typescript-eslint#890]
# Known Issues

- [ ] Problems with parsing Vue SFC (#883)
- [X] ~~Errors when parsing files in watch mode (/ ide plugins) (#864)~~
- [X] ~~Errors when parsing files with the same name in the same folder (#955)~~ 

---

This issue will serve as a mega-thread of sorts for parsing issues.
There's a lot of people posting in various issues about the same problems, and people mixing up which issue is which.

In v2 we released a breaking change which causes the parser to hard fail for files that are not properly included within your project's tsconfig(s). This was done because we noticed that we had a huge performance issue - when we attempted to parse a file that _wasn't_ included in an existing tsconfig, then we would have to parse that file as if it were a brand new project - including all of its dependencies. This was slow, and educating users about the correct configs was near impossible because we can only do it via looking at copy pasted configs in issue threads.

We throw an error so that you can see what files have not been included by typescript based on the config that you have provided. Chances are that you need to reconfigure your tsconfig's `include` so that it properly encapsulates all of the files you want to lint. The best way to do this is [written in the 2.0.0 release notes](https://github.com/typescript-eslint/typescript-eslint/releases/tag/v2.0.0), but I'll copy it here to colocate the information:

# Steps to fix this

1) Upgrade to the [latest `canary` version on npm](https://www.npmjs.com/package/@typescript-eslint/eslint-plugin?activeTab=versions).

2) Create a new config - `tsconfig.eslint.json` - which you pass into parserOptions.project. This new tsconfig should `include` all of the files you want to lint, e.g.:

```jsonc
{
  // extend your base config so you don't have to redefine your compilerOptions
  "extends": "./tsconfig.json",
  "include": [
    "src/**/*.ts",
    "test/**/*.ts",
    "typings/**/*.ts",
    // etc
    
    // if you are going to parse JS files
    "src/**/*/.js"
    // etc
  ]
}
```

If you are using non standard file extensions (i.e. .vue files), you should setup your config something like the following:
```jsonc
{
  "parserOptions": {
    "extraFileExtensions": [".vue"]
  }
}
```

---

# FAQ

### I upgraded to v2 and now I have parsing errors that I didn't have before, why?

See above. If you attempt the above steps, and it doesn't fix the errors, please respond to this post using [this issue template](https://gist.githubusercontent.com/bradzacher/4a399b5892f4e7719c981a9e017d5f5a/raw/989c05edbaed28d6b3a3f8f9508e20e46dfcd967/template.md). Comments asking for help without this template will be deleted. Please, help us to help you.

### I am getting errors in my IDE (VSCode, WebStorm, etc).

First, check to make sure you can do a lint run for your entire project from the CLI (i.e. `yarn eslint`). If you get errors here, then stop, and see above.

If you get no errors, then you've hit a known issue. Sit tight, we're working on a fix.

If and only if you have no errors in the CLI, and it's causing you too many headaches in your IDE, then consider adding `createDefaultProgram` to your config. See the parser docs for more info. *PLEASE NOTE THAT THIS IS A TEMPORARY FIX THAT SHOULD ONLY BE USED ONCE YOU HAVE NO PARSING ISSUES FROM THE CLI.*

### My project uses Vue SFC's, and I can't seem to get it working.

Have a look at our [example for Vue SFC](https://github.com/typescript-eslint/typescript-eslint/tree/master/tests/integration/fixtures/vue-sfc) that we're testing against. Check that your config is the same.

If you're still seeing issues, please respond to this post using [this issue template](https://gist.githubusercontent.com/bradzacher/4a399b5892f4e7719c981a9e017d5f5a/raw/989c05edbaed28d6b3a3f8f9508e20e46dfcd967/template.md). Comments asking for help without this template will be deleted. Please, help us to help you.

**Comment by nhiicts** [comment]
Hi. I'm using @typescript-eslint/parser version 2.0.0 and I have a problem on VSCode IDE. Everything is ok except babel.config.js, index.js, metro.config.js files. It said that 
```
Parsing error: If "parserOptions.project" has been set for @typescript-eslint/parser, .../babel.config.js must be included in at least one of the projects provided.
```
This is my tsconfig.json
```
{
  "compilerOptions": {
    "target": "es2015",
    "module": "es2015",
    "jsx": "react-native",
    "lib": [
      "dom",
      "es2015",
      "es2016"
    ],
    "noEmit": true,
    "pretty": true,
    "allowSyntheticDefaultImports": true,
    "forceConsistentCasingInFileNames": true,
    "experimentalDecorators": true,
    "declaration": false,
    "noImplicitAny": false,
    "preserveConstEnums": true,
    "allowJs": true,
    "moduleResolution": "node",
    "types": [],
    "skipLibCheck": true,
    "version": true,
    "importHelpers": true,
    "noEmitHelpers": true,
    "sourceRoot": "src",
    "noUnusedLocals": false,
    "sourceMap": true
  },
  "filesGlob": [
    "node_modules/redux/index.d.ts",
    "./**/*.ts",
    "./**/*.tsx"
  ],
  "include": [
    "src/**/*"
  ],
  "exclude": [
    "index.js",
    "metro.config.js",
    "babel.config.js",
    "node_modules",
    "__tests__",
    "ios",
    "android",
    "__mocks__",
    "scripts",
    ".vscode"
  ],
  "compileOnSave": false,
}
```
Could you help me?

**Comment by fregante** [comment]
I'm also seeing this import-related issue that I don't see reported anywhere else:

>   ✖    5:35  Parse errors in imported module intervalometer: If "parserOptions.project" has been set for @typescript-eslint/parser, ./node_modules/intervalometer/dist/intervalometer.es-modules.js must be included in at least one of the projects provided. (undefined:undefined)           import/namespace

Should tsconfig's `include` property also have `node_modules`?

**Comment by bradzacher** [comment]
@fregante - could you please fill out the template that's mentioned in the OP?
I can't help you without more information about your config / project - just an error message by itself is too vague to tell.

Help me to help you.

**Comment by fregante** [comment]
My bad, I missed that link. I ended up reverting the v2 install and now I don't see that error anymore even if I restore it. I hid my comment.

**Comment by toddbluhm** [comment]
- [ x] I certify that I have read the OP, and attempted the listed steps to fix.

The issue appears to occur when I have two files with the same name (`fixture.ts` & `fixture.js`) in the same folder (`src`). It only picks up the `.ts` file and will not pick up the `.js` file. Instead, it gives the error that `fixture.js` was not included in the project.

I discovered this issue in my PR here: https://github.com/standard/eslint-config-standard-with-typescript/pull/135

Not even sure if this is a bug or just a known limitation, but wanted to note it in case it was a bug.

---

<details>
<summary>**tsconfig.json**</summary>


```jsonc
{
  "extends": "./node_modules/tsconfigs/universal",
  "compilerOptions": {
    "esModuleInterop": true,
    "importHelpers": false
  }
}
```

</details>

---

<details>
<summary>**tsconfig.eslint.json**</summary>


```jsonc
{
  "extends": "./tsconfig.json",
  "compilerOptions": {
    "allowJs": true,
    "checkJs": true
  },
  "include": [
    "src/**/*",
    "*.ts",
    "*.js"
  ]
}
```

</details>

---

<details>
<summary>**.eslintrc.json**</summary>

```jsonc
{
  "extends": "./lib/index.js",
  "parserOptions": {
    "project": "./tsconfig.eslint.json"
  }
}
```

</details>

---

<details>
<summary>**Example file paths that are throwing errors**</summary>

- `/Users/toddbluhm/Development/Github/eslint-config-standard-with-typescript/src/fixture.js`
  - Parsing error: "parserOptions.project" has been set for @typescript-eslint/parser.
The file does not match your project config: /Users/toddbluhm/Development/Github/eslint-config-standard-with-typescript/src/fixture.js.
The file must be included in at least one of the projects provided

</details>

---

**Versions**

| package                                 | version |
| --------------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin`      | `2.0.0` & `2.0.1-alpha.27` |
| `@typescript-eslint/parser`             | `2.0.0` & `2.0.1-alpha.27` |
| `TypeScript`                            | `3.5.3` |
| `node`                                  | `10.15.0` |

**Comment by bradzacher** [comment]
Hmmm. I ran into similar issues the other week - not with our parser, but with vscode's typescript plugin (and ts-jest). We specifically do not lint fixture files though.

I was [creating test fixtures to thoroughly test the new error messages](https://github.com/typescript-eslint/typescript-eslint/tree/master/packages/typescript-estree/tests/fixtures/invalidFileErrors), and as you can see I have `js/included.jsx` and `js/included.js`, and `ts/included.tsx` and `ts/included.ts`. 

This was causing ts-jest to throw errors during testing, because (when compiled) the files output the same filename. I ended up ignoring that specific diagnostic in ts-jest to make it work:

https://github.com/typescript-eslint/typescript-eslint/blob/65eb99348c8694fc1437f6b601454d2ad0e2834f/packages/typescript-estree/jest.config.js#L13-L20

@toddbluhm - could you confirm for me - if you delete/rename `fixture.ts`, do the errors for `fixture.js` go away?

@uniqueiniquity - if it is the same diagnostic causing an issue. Do you know if we can ignore the diagnostic and let both files be parsed?

**Comment by saostad** [comment]
I have the error message for each newly created .ts file, I should reload my editor window and it will be ok!

**Comment by toddbluhm** [comment]
@bradzacher I can confirm that deleting `fixture.ts` and keeping `fixture.js` causes the "not included in project" error to go away. So by deleting either `fixture.ts` or `fixture.js` causes the "not included in project" error to go away. Keeping both files, causes the error to show up.

**Comment by ahuglajbclajep** [comment]
It seems that `*.tsx` is not supported.
Is there any plan to support it?

**Comment by bradzacher** [comment]
> It seems that `*.tsx` is not supported.
> Is there any plan to support it?

@ahuglajbclajep - TSX is supported, 100%.
Please fill out the template as per the OP. Help me to help you.

**Comment by ahuglajbclajep** [comment]
- [x] I certify that I have read the OP, and attempted the listed steps to fix.

`*.ts` is parsed, but `*.tsx`, `*.js`, and `*.jsx` are not parsed.

---

<details>
<summary>**tsconfig.json**</summary>



```jsonc
{
  "compilerOptions": {
    "target": "es6",
    "module": "esnext", // for dynamic import
    "allowJs": true,
    "jsx": "react",
    "sourceMap": true,
    "outDir": "dist", // for allowJs
    "strict": true,
    "moduleResolution": "node",
    "esModuleInterop": true
  },
  "include": ["src/**/*.ts", "src/**/*.tsx", "src/**/*.js", "src/**/*.jsx"]
}
```

</details>

---

<details>
<summary>**.eslintrc**</summary>

```jsonc
{
  "parser": "@typescript-eslint/parser",
  "parserOptions": { "project": "./tsconfig.json" },
  "env": { "browser": true, "es6": true, "worker": true }, // for allowJS
  "settings": { "react": { "version": "detect" } },
  "plugins": ["@typescript-eslint", "react-hooks"],
  "extends": [
    "eslint:recommended",
    "plugin:@typescript-eslint/eslint-recommended",
    "plugin:@typescript-eslint/recommended",
    "plugin:@typescript-eslint/recommended-requiring-type-checking",
    "plugin:react/recommended",
    "prettier",
    "prettier/@typescript-eslint",
    "prettier/react"
  ],
  "rules": {
    "react-hooks/rules-of-hooks": "error",
    "react-hooks/exhaustive-deps": "warn",
    "react/prop-types": "off"
  },
  "overrides": [
    {
      "files": ["*.js", "*.jsx"],
      "rules": { "@typescript-eslint/explicit-function-return-type": "off" }
    }
  ]
}
```

</details>

---

<details>
<summary>**Example file paths that are throwing errors**</summary>

- `src/foo.tsx`
  - Parsing error: "parserOptions.project" has been set for @typescript-eslint/parser.
    The file does not match your project config: src/foo.tsx.
    The file must be included in at least one of the projects provided.
- `src/bar.js`
  - Parsing error: "parserOptions.project" has been set for @typescript-eslint/parser.
    The file does not match your project config: src/bar.js.
    The file must be included in at least one of the projects provided.
- `src/baz.jsx`
  - Parsing error: "parserOptions.project" has been set for @typescript-eslint/parser.
    The file does not match your project config: src/baz.jsx.
    The file must be included in at least one of the projects provided.

</details>

---

**Versions**

| package                                 | version |
| --------------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin`      | `2.1.1-alpha.4` |
| `@typescript-eslint/parser`             | `2.1.1-alpha.4` |
| `TypeScript`                            | `3.5.3` |
| `node`                                  | `10.16.3` |
| `Visual Studio Code`                    | `1.38.0` |

**Comment by munierujp** [comment]
After creating `tsconfig.eslint.json`, can I use `tsconfig.eslint.json` instead of `tsconfig.json` in `.eslintrc.json`?

`.eslintrc.json`

```json
{
  "extends": "standard-with-typescript",
  "parserOptions": {
    "project": "./tsconfig.eslint.json"
  }
}
```

It seems to work correctly for me.

**Comment by bradzacher** [comment]
yes, definitely. The point of creating the new tsconfig file is so that you can use it there.
